trainer:
  devices: 1        # Set this to 1 for CPU-only
  accelerator: cpu  # Force CPU usage
  num_nodes: 1
  max_epochs: 10
  enable_checkpointing: False
  logger: false


model:
  nemo_path: ${MODEL_DIR}/baseball_stat_model.nemo  # Save model here
  data_dir: ./data
  class_labels:
    intent_labels_file: ./data/intent_labels.csv
    slot_labels_file: ./data/slot_labels.csv
  intent_loss_weight: 0.6
  pad_label: -1
  ignore_start_end: true

  train_ds:
    prefix: trainingData
    batch_size: 26
    shuffle: true

  validation_ds:
    prefix: validationData
    batch_size: 10
    shuffle: false

  test_ds:
    prefix: testData
    batch_size: 13
    shuffle: false

  tokenizer:
    tokenizer_name: bert-base-uncased

  language_model:
    pretrained_model_name: bert-base-uncased
    max_seq_length: 64

exp_manager:
  exp_dir: ./models
  name: "BaseballStatsBot"
  create_tensorboard_logger: true
  create_checkpoint_callback: true
